# Generated by Django 4.2.30 on 2026-06-12 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediahub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrating',
            name='media_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='userrating',
            name='poster_path',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
